name: camera
description: Fork of official camera package to add support for torch
version: 1.0.0+1

homepage: https://github.com/mehulcs/camera-with-flash

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^0.5.0
  video_player: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
      ios:
        pluginClass: CameraPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
